# Server Configuration (Runs on port 8082 since user-service uses 8081)
server.port=8082

# Project Name
spring.application.name=request-service

# Database Configuration for XAMPP MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/relieflink_request_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect